# Generated by Django 2.2.4 on 2019-08-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='atrist',
            new_name='artist',
        ),
    ]
